version: '2'
services:
  vercel-demo:
    image: vercel-demo
    build:
      context: ../../
    container_name: vercel-demo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  r_server:
    image: r_server
    build:
      context: ../../server
    ports:
      - "8081:8081"
