version: "2"
services:
  rowthtech:
    image: vercel-demo
    build: ../src
    container_name: vercel-demo
    ports:
        - 3000:3000
    environment:
        - PORT=3000
  r_server:
    image: r_server
    build: ../server
    ports:
      - 8081:8081
   


